# Generated by Django 3.1.4 on 2020-12-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_grader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncaseresult',
            name='test_case_number',
            field=models.IntegerField(default=0, verbose_name='Test Case Number'),
            preserve_default=False,
        ),
    ]
