# Generated by Django 3.1.4 on 2021-01-05 00:09

import django.db.models.deletion
from django.db import migrations, models

import py_grader.models


class Migration(migrations.Migration):
	dependencies = [
		('py_grader', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='netid',
			name='first_name',
			field=models.CharField(blank=True, max_length=255, verbose_name='First Name'),
		),
		migrations.AddField(
			model_name='netid',
			name='last_name',
			field=models.CharField(blank=True, max_length=255, verbose_name='Last Name'),
		),
		migrations.AddField(
			model_name='netid',
			name='name',
			field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
		),
		migrations.AlterField(
			model_name='assignment',
			name='allowed_packages',
			field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Allowed Packages'),
		),
		migrations.CreateModel(
			name='TestCaseFile',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('test_case_file',
				 models.FileField(upload_to=py_grader.models.content_file_name, verbose_name='Test Case File')),
				('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py_grader.testcase',
				                                verbose_name='Test Case')),
			],
		),
	]
